name: fitness
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cached_network_image: ^3.3.0
  flutter_reorderable_list: ^1.3.1
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  provider: ^6.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/.
